server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /incidents {
        proxy_pass http://backend:3001/incidents;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /techniciens {
        proxy_pass http://backend:3001/techniciens;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /interventions {
        proxy_pass http://backend:3001/interventions;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        proxy_pass http://backend:3001/health;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }
}
