sonar.projectKey=cicd-frontend
sonar.projectName=CI/CD Frontend
sonar.projectVersion=1.0
sonar.sources=app
sonar.exclusions=**/node_modules/**,**/.next/**,**/out/**
sonar.coverage.exclusions=**/*
sonar.sourceEncoding=UTF-8
